// MenuData.js  (meal -> category -> items)

const menuData = {
  Breakfast: {
    "Breakfast Items": [
      "Aloo Paratha",
      "Paneer Paratha",
      "Gobi Paratha",
      "Poha",
      "Bedmi Puri",
      "Chole Kulche",
      "Besan Chilla",
      "Methi Paratha",
      "Poori Bhaji",
      "Stuffed Kulcha",
      "Sooji Upma",
      "Moong Dal Cheela",
      "Idli",
      "Medu Vada",
      "Plain Dosa",
      "Masala Dosa",
      "Rava Dosa",
      "Set Dosa",
      "Uttapam",
      "Pongal",
      "Appam with Stew",
      "Neer Dosa",
      "Pesarattu",
      "Luchi Aloo Torkari",
      "Kochuri",
      "Radhaballavi",
      "Aloor Chop",
      "Piyaji",
      "Ghugni with Bread",
      "Chhana Poda Toast",
      "Vegetable Stuffed Paratha",
      "Pakhala with Sides",
      "Beguni",
      "Kanda Poha",
      "Dhokla",
      "Khandvi",
      "Handvo",
      "Thepla",
      "Muthia",
      "Pav (Maska/Usal)",
      "Mini Pav Bhaji",
      "Batata Poha",
      "Khichu",
    ],
    "Hot Beverages": [
      "Masala Chai",
      "Cardamom Chai",
      "Badam Milk",
      "Tulsi Tea",
      "Ginger Tea",
      "Filter Coffee",
      "Ginger Lemon Tea",
      "Pepper Milk",
      "Cardamom Milk",
      "Rasam Shots",
      "Green Tea",
      "Lemon Tea",
      "Milk Tea",
      "Elaichi Chai",
      "Kokum Warm Drink",
    ],
  },

  Lunch: {
    Starters: [
      "Paneer Tikka",
      "Hara Bhara Kebab",
      "Tandoori Mushroom",
      "Malai Broccoli",
      "Veg Seekh Kebab",
      "Corn Tikki",
      "Stuffed Paneer Pakoda",
      "Crispy Baby Corn",
      "Tomato Dhaniya Shorba",
      "Sweet Corn Soup",
      "Masala Vada",
      "Mysore Bonda",
      "Baby Corn 65",
      "Banana Fry",
      "Pepper Paneer Fry",
      "Rasam Shots",
      "Tomato Rasam Soup",
      "Coconut Milk Veg Soup",
      "Ghugni Chaat",
      "Jhalmuri",
      "Puchka",
      "Mochar Chop",
      "Beguni",
      "Piyaji",
      "Veg Momos",
      "Pakoda Chaat",
      "Ginger Lemon Soup",
      "Sev Puri",
      "Ragda Pattice",
      "Bhel Puri",
      "Khandvi Rolls",
      "Patra",
      "Dabeli Bites",
      "Batata Vada",
      "Farsan Platter",
      "Handvo Bites",
    ],
    "Main Course": [
      "Paneer Butter Masala",
      "Dal Makhani",
      "Shahi Kofta",
      "Chole Masala",
      "Rajma",
      "Palak Paneer",
      "Kadhi Pakora",
      "Baingan Bharta",
      "Navratan Korma",
      "Sambar",
      "Avial",
      "Veg Kurma",
      "Chettinad Veg Curry",
      "Kara Kuzhambu",
      "Mor Kuzhambu",
      "Vegetable Stew",
      "Beans Poriyal",
      "Pumpkin Erissery",
      "Shukto",
      "Dalma",
      "Bengali Chanar Dalna",
      "Aloo Posto",
      "Chanar Kalia",
      "Chanar Jhal",
      "Mocha Ghonto",
      "Labra",
      "Pui Shak",
      "Undhiyu",
      "Sev Tamatar",
      "Gujarati Kadhi",
      "Bharwa Bhindi",
      "Dudhi Chana Dal",
      "Panchkutiyu Shaak",
      "Goan Veg Xacuti",
      "Paneer Amti",
      "Tondli Masala",
    ],
    "Rice & Breads": [
      "Jeera Rice",
      "Veg Biryani",
      "Kashmiri Pulao",
      "Matar Pulao",
      "Zafrani Pulao",
      "Garlic Naan",
      "Tandoori Roti",
      "Lachha Paratha",
      "Stuffed Kulcha",
      "Roomali Roti",
      "Bisi Bele Bath",
      "Lemon Rice",
      "Tamarind Rice",
      "Coconut Rice",
      "Curd Rice",
      "Veg Biryani (Hyderabadi)",
      "Malabar Parotta",
      "Neer Dosa",
      "Ragi Roti",
      "Appam",
      "Mishti Pulao",
      "Bhuni Khichuri",
      "Steamed Rice",
      "Aloo Peas Pulao",
      "Gobindo Bhog Rice",
      "Luchi",
      "Kochuri",
      "Radhaballavi",
      "Vegetable Stuffed Paratha",
      "Masala Khichdi",
      "Vaghareli Khichdi",
      "Veg Pulao",
      "Dal Dhokli Rice",
      "Surti Vagharela Bhaat",
      "Bhakri",
      "Rotla",
      "Thepla",
      "Pav",
    ],
    Desserts: [
      "Gulab Jamun",
      "Rasmalai",
      "Jalebi with Rabri",
      "Gajar Ka Halwa",
      "Motichoor Ladoo",
      "Kesar Peda",
      "Besan Barfi",
      "Dry Fruit Ladoo",
      "Mysore Pak",
      "Coconut Laddu",
      "Kesari Bath",
      "Elaneer Payasam",
      "Paal Paniyaram",
      "Badam Halwa",
      "Pineapple Kesari",
      "Rava Kesari",
      "Roshogolla",
      "Mishti Doi",
      "Sandesh",
      "Pantua",
      "Patishapta",
      "Cham Cham",
      "Kheer Kadam",
      "Chhena Gaja",
      "Shrikhand",
      "Basundi",
      "Mohanthal",
      "Puran Poli",
      "Doodh Pak",
      "Sukhdi",
      "Lapsi",
      "Ghari",
    ],
  },

  "Evening Snacks": {
    Snacks: [
      "Aloo Tikki Chaat",
      "Dahi Puri",
      "Papdi Chaat",
      "Pani Puri",
      "Raj Kachori",
      "Dahi Bhalla",
      "Paneer Tikka",
      "Masala Vada",
      "Mysore Bonda",
      "Punugulu",
      "Banana Bonda",
      "Pesarattu",
      "Mini Dosa Rolls",
      "Sundal",
      "Uppu Kozhukattai Bites",
      "Ghugni Chaat",
      "Jhalmuri",
      "Puchka",
      "Aloor Chop",
      "Chanar Cutlet",
      "Veg Momos",
      "Dhoka Cutlets",
      "Moong Dal Bora",
      "Sev Puri",
      "Ragda Pattice",
      "Dhokla Chaat",
      "Khaman Chaat",
      "Muthia",
      "Handvo Bites",
      "Batata Vada",
      "Dabeli Bites",
      "Mini Pav Bhaji Sliders",
      "Farsan Platter",
    ],
    Drinks: [
      "Jaljeera",
      "Rose Sherbet",
      "Sweet Lassi",
      "Masala Buttermilk",
      "Buttermilk",
      "Solkadhi",
      "Lemon Iced Tea",
      "Nannari Sherbet",
      "Aam Pora Sherbet",
      "Sugarcane Juice",
      "Lemon Tea",
      "Masala Chaas",
      "Kokum Fizz",
    ],
  },

  Dinner: {
    Starters: [
      "Hara Bhara Kebab",
      "Paneer Shashlik",
      "Stuffed Mushroom Caps",
      "Tandoori Mushroom",
      "Malai Broccoli",
      "Tomato Dhaniya Shorba",
      "Pepper Rasam Soup",
      "Coconut Milk Veg Soup",
      "Tomato Rasam",
      "Masala Vada",
      "Medu Vada",
      "Veg Clear Soup",
      "Tomato Dhania Soup",
      "Moong Dal Soup",
      "Chanar Bora",
      "Khandvi Rolls",
      "Patra",
      "Farsan Platter",
      "Ragda Pattice",
      "Sev Puri",
    ],
    "Main Course": [
      "Dal Makhani",
      "Paneer Butter Masala",
      "Shahi Kofta",
      "Kadhi Pakora",
      "Palak Paneer",
      "Baingan Bharta",
      "Aloo Methi",
      "Vegetable Stew",
      "Chettinad Veg Curry",
      "Mor Kuzhambu",
      "Pumpkin Erissery",
      "Beans Poriyal",
      "Avial",
      "Chanar Jhal",
      "Mocha Ghonto",
      "Labra",
      "Bengali Chanar Dalna",
      "Pui Shak",
      "Aloo Posto",
      "Bharwa Bhindi",
      "Dudhi Chana Dal",
      "Panchkutiyu Shaak",
      "Gujarati Kadhi",
      "Paneer Amti",
      "Goan Veg Xacuti",
    ],
    "Rice & Breads": [
      "Veg Fried Rice",
      "Jeera Rice",
      "Zafrani Pulao",
      "Garlic Naan",
      "Missi Roti",
      "Roomali Roti",
      "Lachha Paratha",
      "Veg Biryani (Hyderabadi)",
      "Curd Rice",
      "Coconut Rice",
      "Malabar Parotta",
      "Appam",
      "Adai",
      "Uttapam",
      "Steamed Rice",
      "Gobindo Bhog Rice",
      "Pakhala Rice",
      "Mishti Pulao",
      "Luchi",
      "Kochuri",
      "Vaghareli Khichdi",
      "Surti Bhaat",
      "Veg Pulao",
      "Bhakri",
      "Rotla",
      "Thepla",
      "Pav",
    ],
    Desserts: [
      "Gulab Jamun",
      "Rasmalai",
      "Rabri Mousse",
      "Gulab Jamun Cheesecake",
      "Dry Fruit Brownie",
      "Besan Barfi",
      "Elaneer Payasam",
      "Paal Paniyaram",
      "Kesari Bath",
      "Mysore Pak",
      "Coconut Jaggery Tart",
      "Roshogolla",
      "Mishti Doi",
      "Sandesh",
      "Pantua",
      "Cham Cham",
      "Kheer Kadam",
      "Shrikhand",
      "Basundi",
      "Mohanthal",
      "Puran Poli",
      "Doodh Pak",
      "Sukhdi",
    ],
  },
};

export default menuData;
